services:
  compute:
    build:
      context: app
      target: builder
    container_name: daisi-compute
    ports:
      - '127.0.0.1:8000:8000'
    depends_on: 
      - broker
    networks: ["brokers"]
    restart: "no"

  broker:
    image: nats
    container_name: daisi-broker
    networks: ["brokers"]
    ports:
      - "127.0.0.1:8222:8222"
      - "127.0.0.1:4222:4222"

networks:
  brokers:
    name: brokers
