services:
  compute:
    build:
      context: app
      target: builder
    container_name: daisi-compute
    ports:
      - '127.0.0.1:8000:8000'
    depends_on: 
      - broker
    networks: ["brokers"]
    restart: "no"
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: /app
        # - action: rebuild
        #   path: ./app/requirements.txt

  broker:
    image: nats
    container_name: daisi-broker
    networks: ["brokers"]
    ports:
      - "127.0.0.1:8222:8222"
    # command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "

networks:
  brokers:
    name: brokers
